//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_8000
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public string DNI { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Edad { get; set; }
    }
}
